services:
  - type: web
    name: lector-polizas
    region: oregon
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y poppler-utils tesseract-ocr tesseract-ocr-spa && pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn Lector_pdf:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
